name: Mirror ISL master

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone upstream
        run: |
          git clone https://repo.or.cz/isl.git repo
          cd repo
          git checkout master

      - name: Push master to GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          git remote remove origin || true
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

          git push origin master --force
