name: Mirror from repo.or.cz

on:
  schedule:
    - cron: "0 */6 * * *"     # every 6 hours
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone upstream mirror
        run: |
          git clone --mirror https://repo.or.cz/isl.git repo

      - name: Push to GitHub
        run: |
          cd repo
          git remote remove origin || true
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --mirror
