name: Mirror from repo.or.cz

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allow manual trigger

jobs:
  pull-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare empty directory
        run: |
          rm -rf ./*

      - name: Clone upstream repo (mirror)
        run: |
          git clone --mirror https://repo.or.cz/isl.git repo
          cd repo
          git remote set-url --push origin https://github.com/${{ github.repository }}.git

      - name: Push all refs to GitHub
        run: |
          cd repo
          git push --mirror
